sudo: required

services:
  - docker

git:
    depth: 100500

jobs:
  include:
    - name: "CentOS 7: deploy RPM"
      env: OS=el DIST=7
    - name: "Fedora 26: deploy RPM"
      env: OS=fedora DIST=26
    - name: "Fedora 27: deploy RPM"
      env: OS=fedora DIST=27
    - name: "Fedora 28: deploy RPM"
      env: OS=fedora DIST=26
    - name: "Fedora 29: deploy RPM"
      env: OS=fedora DIST=27

script:
  - git clone https://github.com/packpack/packpack.git
  - ./packpack/packpack

before_deploy:
  - ls -l build/

deploy:
  # Deploy packages to PackageCloud
  - provider: packagecloud
    username: ${PACKAGECLOUD_USER}
    repository: "1_9"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && x"${TRAVIS_EVENT_TYPE}" != x"cron"
  - provider: packagecloud
    username: ${PACKAGECLOUD_USER}
    repository: "1_10"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && x"${TRAVIS_EVENT_TYPE}" != x"cron"
  - provider: packagecloud
    username: ${PACKAGECLOUD_USER}
    repository: "2x"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && x"${TRAVIS_EVENT_TYPE}" != x"cron"

notifications:
  email: true
  irc: false
